import type { Incident, DailySummary } from "./types"

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: "inc_1",
    category: "danger",
    urgency: "high",
    location: {
      lat: 44.435,
      lng: 26.0999,
      address: "Piata Universitatii, Bucharest, Romania",
      distance_km: 0.3,
    },
    description: "Broken glass on sidewalk near subway entrance, dangerous for pedestrians",
    image_url: "/broken-glass-on-sidewalk.jpg",
    reported_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    reported_by: { user_id: "anon_1", trust_score: 4.2 },
    verification: {
      confirmed_count: 3,
      last_confirmed: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
      is_active: true,
    },
    ai_confidence: 0.92,
  },
  {
    id: "inc_2",
    category: "blocked_path",
    urgency: "medium",
    location: {
      lat: 44.4401,
      lng: 26.0865,
      address: "Strada Stirbei Voda, Bucharest, Romania",
      distance_km: 1.2,
    },
    description: "Construction blocking bike lane and sidewalk",
    image_url: "/construction-blocking-sidewalk.jpg",
    reported_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    reported_by: { user_id: "user_234", trust_score: 3.8 },
    verification: {
      confirmed_count: 5,
      last_confirmed: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
      is_active: true,
    },
    ai_confidence: 0.88,
  },
  {
    id: "inc_3",
    category: "protest",
    urgency: "low",
    location: {
      lat: 44.4285,
      lng: 26.103,
      address: "Bulevardul Regina Maria, Bucharest, Romania",
      distance_km: 0.5,
    },
    description: "Peaceful demonstration, expect delays",
    image_url: "/peaceful-street-protest.jpg",
    reported_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    reported_by: { user_id: "anon_2", trust_score: 4.5 },
    verification: {
      confirmed_count: 12,
      last_confirmed: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
      is_active: true,
    },
    ai_confidence: 0.95,
  },
  {
    id: "inc_4",
    category: "event",
    urgency: "low",
    location: {
      lat: 44.4479,
      lng: 26.0979,
      address: "Gara de Nord, Bucharest, Romania",
      distance_km: 1.8,
    },
    description: "Street performers gathering, heavy foot traffic",
    image_url: "/street-performers-crowd.jpg",
    reported_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    reported_by: { user_id: "user_567", trust_score: 4.1 },
    verification: {
      confirmed_count: 7,
      last_confirmed: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      is_active: true,
    },
    ai_confidence: 0.91,
  },
  {
    id: "inc_5",
    category: "crime_alert",
    urgency: "high",
    location: {
      lat: 44.4214,
      lng: 26.1197,
      address: "Bulevardul Decebal, Bucharest, Romania",
      distance_km: 0.7,
    },
    description: "Suspicious activity reported, police on scene",
    image_url: "/police-car-on-street.jpg",
    reported_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    reported_by: { user_id: "anon_3", trust_score: 4.7 },
    verification: {
      confirmed_count: 8,
      last_confirmed: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
      is_active: true,
    },
    ai_confidence: 0.87,
  },
]

export const MOCK_SUMMARY: DailySummary = {
  date: new Date().toISOString().split("T")[0],
  summary: {
    text: "Your area is generally safe today. There are a few construction zones and one high-priority incident to be aware of. Plan your route accordingly.",
    high_priority_count: 2,
    medium_priority_count: 3,
    low_priority_count: 5,
  },
  safety_score: 7.5,
  top_incidents: MOCK_INCIDENTS.slice(0, 3),
  recommendations: [
    "Avoid Times Square area due to broken glass hazard",
    "Consider alternate routes around Central Park West construction",
    "Allow extra time for travel due to demonstration on Broadway",
  ],
}
